name: Full Pipeline and Deployment

on:
  schedule:
    - cron: "0 5 * * *"       # Daily at 7 PM Montreal
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        run: python main.py

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: anime-oracle-479313

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to Artifact Registry
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t northamerica-northeast1-docker.pkg.dev/anime-oracle-479313/my-repo/anime-oracle:latest \
            --push \
            .
